spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/selab_foreign?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
#    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    #redis配置
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          max-idle: 5
          min-idle: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true


server:
  port: 8080
  #  context-path: /stusys
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: UTF-8

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
#mybatis-plus配置
mybatis-plus:
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
    #mybatis-plus日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
      #逻辑删除
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.oddfar.**.domain